default: &default
  config:
    base_url: 'http://gateway.marvel.com'
    characters_path: '/v1/public/characters'
    character_stories_path: '/v1/public/characters/:id/stories'
    stories_characters_path: '/v1/public/stories/:story_id/characters'

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
